export const COFFEE_BRANDS_BY_VALUE = 'COFFEE_BRANDS_BY_VALUE';
export const COFFEE_BRANDS_BY_FACTORY = 'COFFEE_BRANDS_BY_FACTORY';
export const COFFEE_BRANDS_BY_FACTORY_2 = 'COFFEE_BRANDS_BY_FACTORY_2';

export const COFFEE_BRANDS_VALUES = ['buddy brew', 'nescafe'];
